server:
  port: 8081
  servlet:
    context-path: /employee-service
logging:
  config: classpath:log4j2.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Company
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver